import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import Writer from '../domains/shared/components/editor/Writer';
import Viewer from '../domains/shared/components/editor/Viewer';

const Home: NextPage = () => {
  const [isReadOnly, setIsReadOnly] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Writer />
        <Viewer />
        <button onClick={() => setIsReadOnly((prev) => !prev)}>리드온니</button>
      </main>
    </div>
  );
};

export default Home;
